matrix:
  platform:
    - linux/amd64

labels:
  platform: ${platform}
    
steps:
  build-n-test:
    when:
      event: [push]
    image: alpine:latest
    commands:
      - apk update
      - apk add --no-cache bash build-base words-en
      - make
      - gdb -batch -ex "run" -ex "bt" --args dicepwgen
      #- ./dicepwgen -y | grep -E '[a-z]*%'


