matrix:
  platform:
    - linux/amd64

labels:
  platform: ${platform}
    
steps:
  build:
    when:
      event: [push]
    image: alpine:latest
    commands:
      - apk add --no-cache make bash binutils gcc
      - make

